[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "segittur-commons"
version = "0.3.14"
description = "Segittur-Commons is a Python package that provides common utilities and components for SEGITTUR projects."
authors = [
  { name = "Alejandro Arrabal Hidalgo", email = "alejandro.arrabal@sngular.com" },
  { name = "Sofía Cerdá Muñoz", email = "sofia.cerda@sngular.com" }
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "langchain (==0.3.27)",
    "langchain-openai (>=0.3.32,<0.4.0)",
    "langchain-text-splitters (>=0.3.0,<0.4.0)",
    "langchain-milvus (>=0.2.0,<0.3.0)",
    "langfuse (==3.6.1)",
    "owlready2 (==0.48)",
    "pydantic-settings (>=2.0,<3.0)",
    "azure-storage-blob (>=12.25.1,<12.26.0)",
    "azure-identity (>=1.23.0,<1.24.0)",
    "minio (==7.2.18)",
    "pycasbin (>=1.4.0,<2.0.0)",
    "python-keycloak (>=5.8.1,<5.9.0)",
    "pyyaml (>=6.0.2,<6.1.0)",
    "graypy (>=2.1.0,<2.2.0)",
    "arcgis (>=2.4.1)",
    "geojson-pydantic (>=2.1.0)"
]

[tool.poetry]
name = "segittur-commons"
package-mode = true
packages = [{ include = "segittur_commons" }]

[tool.poetry.group.dev.dependencies]
pip-audit = "~2.9"
pytest = "~8.3"
pytest-asyncio = "~0.25"
pytest-cov = "~6.1"
coverage = "~7.6"
factory-boy = "~3.3"

[tool.poetry.group.quality]
optional = true

[tool.poetry.group.quality.dependencies]
ruff = "*"
mypy = "*"
black = "*"
types-requests = "*"

[tool.poetry.group.security]
optional = true

[tool.poetry.group.security.dependencies]
bandit = "*"

[tool.black]
line-length = 100
exclude = '''
(
  /(
    | \.git          # root of the project
  )/
)
'''

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = [ "tests" ]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
no_implicit_optional = false
