services:

  app:
    container_name: commons-dev
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        UID: $UID
        GID: $GID
        USER: $USER
        WORKSPACE_FOLDER: $WORKSPACE_FOLDER
    user: $UID:$GID
    volumes:
      - ..:${WORKSPACE_FOLDER}/
    env_file:
      - .env
    networks:
      - avc_network

networks:
  avc_network:
    external: true